steps:
 
  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/desafio-CI-goLang:latest', './devops/docker/desafio-CI-goLang/']



images:
  - 'gcr.io/$PROJECT_ID/desafio-CI-goLang:latest'
